### PR TITLE
fix lint warnings #45

### PR DESCRIPTION
**Pull request by kraftman**
Fixed as many lint warnings as I could from my understanding of the repo, the bulk that are remaining are 'JSX props should not use arrow functions' but I'm not sure what you want to do about those design-wise.

### CODE REVIEW

**Comment by lexoyo** [comment]
Nice !!!

**Comment by JbIPS** [comment]
Thank you for caring about linting! 😃

**Comment by kraftman** [comment]
Removed the package-lock.json change i didnt mean to commit and removed the comment as recommended.

**Comment by JbIPS** [comment]
Thanks a lot!

**Pull request merged**
